### ISSUE TITLE
Issue on Creating classroom

### ISSUE THREAD

**Issue by reckless-sergio** [ChannelizeIO/Channelize-Whiteboard-SDK#5]
I am getting below error after trying to create a one to one classroom and I have also attached image for refrence. 

> TypeError: Cannot read property 'getDocument' of undefined

![image](https://user-images.githubusercontent.com/3600301/98073832-30a1d180-1e8f-11eb-9ea5-7958c83d26d9.png)

I am seeing that PDFJS is undefined in console

![image](https://user-images.githubusercontent.com/3600301/98073981-84acb600-1e8f-11eb-838a-3ae76e3b9e23.png)
![image](https://user-images.githubusercontent.com/3600301/98073997-8d04f100-1e8f-11eb-8331-8cb94d9b4d91.png)

**Comment by ankit-gupta-bs** [comment]
Hi @maheshvemuri ,

I am really sorry to hear about your issue with the Whiteboard. I have looked into your problem and it seems to be a bug. You're the first person to report this, so Thank you! I have added this issue to our to-do list. We have already started working on this and we are expecting it to be solved by Friday. 

Hope that is fine with you.

**Comment by ankit-gupta-bs** [comment]
Hi @maheshvemuri ,

Thanks for having patience, we have updated the code in the master branch, please have a look also let us know in case if you still have any issues we will be more than happy to help you.
