### ISSUE TITLE
Agora Video Calling not Visible

### ISSUE THREAD

**Issue by mohit67890** [ChannelizeIO/Channelize-Whiteboard-SDK#8]
Hi, I'm trying to run this project locally. The whiteboard is working fine but the agora video and the panel on the right side is not visible as its running on the demo website. 
Am I missing out anything here? Can you help please

**Comment by ankit-gupta-bs** [comment]
Hi @mohit67890 , 

For the sample video calling code, please check here:
https://github.com/AgoraIO

Please let us know if you have any queries about the Whiteboard's features and we will be happy to help you.
